### ISSUE TITLE
How to add SSPCAB to the classification model?

### ISSUE THREAD

**Issue by nico-zck** [ristea/sspcab#3]
In your paper, you said "we generally replace the penultimate convolutional layer with SSPCAB". It sounds reasonable to do this for reconstruction models, since their penultimate layer usually have high-res and low-level features for reconstructing.
But the penultimate layer of a classification model, e.g., CutPaste, has a very low-res and high-level feature map. Does SSPCAB still be applied as the same way?

**Comment by ristea** [comment]
Yes. It is applied in the same way for CutPaste approach. It is introduced in the penultimate conv layer of the model.

**Comment by tylgczq** [comment]
> Yes. It is applied in the same way for CutPaste approach. It is introduced in the penultimate conv layer of the model.

For example, in HF2VAD, we should apply the sspcab in the penultimate conv layer of CVAD, rather than in the penultimate conv layer of ML_MemAE-SC?
